on: [push, pull_request]
name: CICD
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v ./...
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Binary
      run: GOOS=linux go build -o main
    - name: Zip
      run: zip function.zip main
    - name: Upload deploy package
      uses: actions/upload-artifact@v2
      with:
        name: function
        path: function.zip
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Init
      working-directory: terraform
      run: terraform init
    - name: Terraform Format
      working-directory: terraform
      run: terraform fmt -check
    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan


#  publish:
#    needs: [test]
#    name: Publish docker image
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Push to Docker Hub
#      uses: docker/build-push-action@v1
#      if: startsWith(github.ref, 'refs/tags/v') 
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        repository: dreddick/go-slack-icebreaker
#        tag_with_ref: true
#        tag_with_sha: true